# Trigger the pipeline on /src pushes to the main branch
trigger:
  branches:
   include:
     - main
   paths:
    include:
      - infra/*

# Do not trigger the pipeline on pull requests
pr:
  branches:
    exclude:
      - '*'


pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: 'DeployToTest'
  displayName: 'Deploy Infrastucture To Test'
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: Test
    variables:
    - group: DertInfoImageResizeV4_Infrastucture_Staging_VariablesGroup
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              connectedServiceName: '$(connectedServiceName)'
              location: '$(location)'
              resourceGroupName: '$(resourceGroupName)'
              csmFile: '$(csmFile)'
              csmParametersFile: '$(csmParametersFile)'
              overrideParameters: >
                -environmentTag stg

- stage: 'DeployToLive'
  displayName: 'Deploy API to Live'
  dependsOn: DeployToTest
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: Live
    variables:
    - group: DertInfoImageResizeV4_Infrastucture_Production_VariablesGroup
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              connectedServiceName: '$(connectedServiceName)'
              location: '$(location)'
              resourceGroupName: '$(resourceGroupName)'
              csmFile: '$(csmFile)'
              csmParametersFile: '$(csmParametersFile)'
              overrideParameters: >
                -environmentTag prod