# Trigger the pipeline on /src pushes to the main branch
trigger:
  branches:
   include:
     - main
  paths:
    include:
      - infra

# Do not trigger the pipeline on pull requests
pr:
  branches:
    exclude:
      - '*'
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'BuildArtefact'
  displayName: 'Create Artefact IaC'
  jobs:
    - job: 'CopyIaC'
      displayName: 'Copy the IaC files frim "infra" to "iac"'
      steps:
        - task: PublishPipelineArtifact@1
          displayName: 'PublishInfrastiuctureAsCode'
          inputs:
            targetPath: 'infra'
            artifact: 'iac'

- stage: Lint
  jobs:
  - job: LintCode
    displayName: Lint code
    steps:
      - script: |
          az bicep build --file infra/deploy.bicep
        name: LintBicepCode
        displayName: Run Bicep linter             
  
- stage: 'DeployToTest'
  displayName: 'Deploy Infrastucture To Test'
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: Test
    variables:
    - group: DertInfoImageResizeV4_Infrastucture_Staging_VariablesGroup
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'iac'
              downloadPath: '$(System.ArtifactsDirectory)'
              cleanDestinationFolder: true
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '(JUL2024) Visual Studio Professional Subscription (9ee4f83c-a9a6-41a0-822d-13e18dc6c648)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.ArtifactsDirectory)/main.bicep'
              csmParametersFile: '$(System.ArtifactsDirectory)/parameters-main-stg.json'
              overrideParameters: '-environmentTag stg'
              deploymentMode: 'Incremental'

- stage: 'DeployToLive'
  displayName: 'Deploy API to Live'
  dependsOn: DeployToTest
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: Live
    variables:
    - group: DertInfoImageResizeV4_Infrastucture_Production_VariablesGroup
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'iac'
              downloadPath: '$(System.ArtifactsDirectory)'
              cleanDestinationFolder: true
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              connectedServiceName: '(JUL2024) DertInfo Subscription (e9f1da4f-d34f-4e93-b7c9-75d375a60253)'
              location: '$(location)'
              resourceGroupName: '$(resourceGroupName)'
              csmFile: '$(System.ArtifactsDirectory)/deploy.bicep'
              csmParametersFile: '$(System.ArtifactsDirectory)/deploy-params-prod.json'
              overrideParameters: >
                -environmentTag prod