# Trigger the pipeline on /src pushes to the main branch
trigger:
  branches:
   include:
     - main
  paths:
    include:
      - src

# Do not trigger the pipeline on pull requests
pr:
  branches:
    exclude:
      - '*'
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'BuildArtefact'
  displayName: 'Move IaC files to drop'
  jobs:
    - job: 'CopyIaC'
      displayName: 'Copy he IaC from Source into artefact to support redeployment'
      steps:
        - task: PublishPipelineArtifact@1
          displayName: 'PublishInfrastiuctureAsCode'
          inputs:
            targetPath: 'infra'
            artifact: 'iac'
          
  
- stage: 'DeployToTest'
  displayName: 'Deploy Infrastucture To Test'
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: Test
    variables:
    - group: DertInfoImageResizeV4_Infrastucture_Staging_VariablesGroup
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: iac
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '(JUL2024) Visual Studio Professional Subscription (9ee4f83c-a9a6-41a0-822d-13e18dc6c648)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: 'deploy.bicep'
              csmParametersFile: 'deploy-params-stg.json'
              overrideParameters: '-environmentTag stg'
              deploymentMode: 'Incremental'

- stage: 'DeployToLive'
  displayName: 'Deploy API to Live'
  dependsOn: DeployToTest
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: Live
    variables:
    - group: DertInfoImageResizeV4_Infrastucture_Production_VariablesGroup
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: iac
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              connectedServiceName: '(JUL2024) DertInfo Subscription (e9f1da4f-d34f-4e93-b7c9-75d375a60253)'
              location: '$(location)'
              resourceGroupName: '$(resourceGroupName)'
              csmFile: '$(csmFile)'
              csmParametersFile: '$(csmParametersFile)'
              overrideParameters: >
                -environmentTag prod